cr=/cygdrive/c/user/oleg/git/e3work/art/oleg/crcl/crcl_w.exe

all: superenc.ttb

superenc.ttb:
	$(cr) -bgc bbs
	rm -f superenc.ttb
	$(cr) -ct superenc
	$(cr) superenc

clean:
	rm -f bbs.*.cir *.ttb
